### ISSUE TITLE
SPI programming procedure

### ISSUE THREAD

**Issue by tescott-jdes** [FaradayA600Platform/U-Boot#1]
Are there plans to describe the procedure to update the SPI on the A600 EVB with a custom U-Boot?

**Comment by FaradayA600Platform** [comment]
Hi:
It is fine to use U-boot "sf" command to update the content of SPI flash.
We will update the memory layout and sequence in the wiki later.

**Comment by tescott-jdes** [comment]
The latest Wiki updates look to address this.  Thank you!
